### ISSUE TITLE
[Bug] Redirect URI is set to http instead of https when deploying to Azure App Service for Docker container (Linux)

### ISSUE THREAD

**Issue by mochr** [AzureAD/microsoft-identity-web#115]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft Identity Web 1.0.0-preview

**Where is the issue?**
* Web App
    * [ x ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (Validating tokens)
    * [ ] Protected web APIs (Validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In Memory caches
     * [ ] Session caches
     * [ ] Distributed caches

Other? - please describe;
Probably valid for most cases.

**Is this a new or existing app?**

This is an experiment to test an app with Microsoft.Identity.Web deployed to Azure App Service for Docker Containers.

**Repro**
1. Open example [1-2-AnyOrg](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-2-AnyOrg)
1. Add Docker support in Visual Studio (create standard Dockerfile)
1. Build image
1. Publish to container registry
1. Create a new App Service using the container image
1. Add configuration
1. Browse new web app, and you will be redirected to login.microsoftonline.com as expected, but with `redirect_uri=http%3A%2F%2F<your app service name>.azurewebsites.net%2Fsignin-oidc` instead of `redirect_uri=https%3A%2F%2F<your app service name>.azurewebsites.net%2Fsignin-oidc` .
1. Manually changing the redirect URI to HTTPS will enable authentication and the app will work as expected.

**Expected behavior**
Expected to be redirected to the HTTPS-page.

**Actual behavior**
Error AADSTS50011 is shown in the browser, as there is a mismatch between registered redirect-URIs.

**Possible Solution**
Maybe there is a way to configure the App Service to avoid this issue? Or is there a way to configure Microsoft.Identity.Web to use HTTPS in the redirect URI?

**Additional context/ Logs / Screenshots**
The application log shows the following:
`Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]: Failed to determine the https port for redirect. `

There is a hint [here](https://techcommunity.microsoft.com/t5/azure-app-service/things-you-should-know-web-apps-and-linux/ba-p/392472#NoSSL) that SSL should not be enabled in the web app, but how is it possible to not have SSL enabled in the web app, but still have HTTPS in the redirect URI?

**Comment by BurritoSmith** [comment]
I'm seeing the same behavior using example 1-1, deployed to a regular Azure App Service (not docker).  Reply urls in azure are set to https, "domain" in the appsettings.json is set to https, but when I try to use the login mechanism, it's passing http as my reply url.  Works fine in localhost while debugging.

**Comment by jmprieur** [comment]
@BurritoSmith : did you add the right redirect URIs (with https:) in the app registration for your application?

**Comment by jmprieur** [comment]
## Spec

### Why?
In order to avoid customers to have to update the redirect URI in the code when they deploy their Web apps, the redirect URI is computed automatically by Microsoft.Identity.Web (in `TokenAcquisition.BuildConfidentialClientApplicationAsync`).

Note that this does not prevent developers to add redirect URI in the app registration portal, but this allow them to have the same code for debugging locally and for deployed applications if they wish to.

https://github.com/AzureAD/microsoft-identity-web/blob/c2f81fd6b7be240046350124311835885051972f/src/Microsoft.Identity.Web/TokenAcquisition.cs#L334-L338

Although this solves many cases, there are cases (like working in containers, or with reverse proxys), where this is not flexible enough

### What?
The proposal is to check the `_microsoftIdentityOptions.CallbackPath` uri (for instance by tyring to build a Uri instance with [Uri.TryCreate](https://docs.microsoft.com/en-us/dotnet/api/system.uri.trycreate)(_microsoftIdentityOptions.CallbackPath. UriKind.RelativeOrAbsolute, out uri)

If this is an absolute URI ([IsAbsoluteUri](https://docs.microsoft.com/en-us/dotnet/api/system.uri.isabsoluteuri)), use it directly as `currentUri`, this will bring the flexibility to the developers to decide the full reply URI.

If this is not an absolute URI, do as is done today (the default)

**Comment by BurritoSmith** [comment]
@jmprieur yes, the redirect URIs in the app registration are set to https.  I actually mis-informed you yesterday when I said my app was hosted on azure (it was late in the day and I was tired and confused about which particular one this was....).  This particular app is an internal one that is hosted behind a load balancer.  The nodes host the application on http using ports to separate each application in IIS but the load balancer accepts https traffic then forwards that on to the nodes over http.  So in this model the nodes seem to be checking themselves and determining that they are being hosted over http and therefore changing the reply url that gets passed up accordingly.  I haven't sniffed the traffic out, but it's possible that in the flow, they're actually passing the machine name that's hosting them rather than the host.domain name we're using to reach our LB. IE http://mymachinename:44200 instead of https://myhost.mydomain.com.  I have seen a few different errors from the MS login about mismatched reply URLs when the machine names are not included.

In any case, being able to override the behavior you described above would be a must for our situation.  We can not rely on our machines accurately obtaining a computed return URL.  I assumed that it was using the "domain" property in the JSON config as the reply url.  To me, you could use that in conjuction with the signin-oidc, or just add another property in the json config for us to manipulate what the reply url should be.

**Comment by jmprieur** [comment]
Thanks for the explanation @BurritoSmith .
and for confirming that the spec above would work for you!

yes, we would use the CallbackPath JSON property:

https://github.com/AzureAD/microsoft-identity-web/blob/813844be0d20ab9284c5ec3bbecdd1ad58cf089a/tests/WebAppCallsWebApiCallsGraph/Client/appsettings.json#L7

**Comment by mochr** [comment]
So am I understanding it correct that the property will be set to the following?
```
"CallbackPath": "https://<app_name>.azurewebsites.net/signin-oidc"
```

That would be perfect for me, and also having the possibility to not specify the full path for local development.

**Comment by BurritoSmith** [comment]
I had a little bit of time this morning to play around with trying to manually add the return URI into the  process.  I was working with the file you mention above @jmprieur (microsoft-identity-web/src/Microsoft.Identity.Web/TokenAcquisition.cs) and wasn't able to get it to inject my return URI into the MS Login GET request with the querystring parameter set to my manual override.  There is obviously something else going on deeper in the plumbing that I didn't dig into.  Just for the heck of it, I also tried updating the CallbackPath property now to an absolute URI and that did not work (as I wouldn't expect it to since this hasn't been implemented in my current version) but it did throw an exception as it was not able to be parsed.

Please let us know when you've implemented your suggested changes so I can come back to this in my project. For now, I've had to roll back to an older version of our OpenID authentication process.

thanks so much.

**Comment by jmprieur** [comment]
@BurritoSmith, we have prioritized fixing this issue (cc: @jennyf19)
Meanwhile, do you want to try the following (in your startup.cs)

```CSharp 
 public void ConfigureServices(IServiceCollection services)
 {
  services.AddSignIn(Configuration);
  services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, 
                                         options => {
 
     var redirectToIdpHandler = options.Events.OnRedirectToIdentityProvider;
     options.Events.OnRedirectToIdentityProvider = async context =>
     {
      // Call what Microsoft.Identity.Web is doing
      await redirectToIdpHandler(context);

     // Override the redirect URI to be what you want
     context.ProtocolMessage.RedirectUri = "your redirect URI";
    };
   });

 // More code here ...
}
```

**Comment by mochr** [comment]
I tested this solution, and it works for sign-in 👍 The sign-out redirect URI (post_logout_redirect_uri) is still http though. You can test the app at [https://demoopenid.azurewebsites.net/](https://demoopenid.azurewebsites.net/).

**Comment by jmprieur** [comment]
@mochr : thanks for confirming.
You can also the post logout URI with `context.ProtocolMessage.PostLogoutRedirectUri = "your post logout URI";` 

Updating the code snippet:

```CSharp 
 public void ConfigureServices(IServiceCollection services)
 {
  services.AddSignIn(Configuration);
  services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, 
                                         options => {
 
     var redirectToIdpHandler = options.Events.OnRedirectToIdentityProvider;
     options.Events.OnRedirectToIdentityProvider = async context =>
     {
      // Call what Microsoft.Identity.Web is doing
      await redirectToIdpHandler(context);

     // Override the redirect URI to be what you want
     context.ProtocolMessage.RedirectUri = "your redirect URI";
     context.ProtocolMessage.PostLogoutRedirectUri = "your post logout URI";
    };
   });

 // More code here ...
}
```

**Comment by mochr** [comment]
Thanks for the suggestion! I tested it and found that I needed to add the post logout URI to the `OnRedirectToIdentityProviderForSignOut` event. This solution works as expected with an added `WebAppURI` parameter in the configuration, but an integrated solution using absolute or relative `CallbackPath`/`SignedOutCallbackPath` would of course be preferable.

https://demoopenid.azurewebsites.net/ has been updated with the code below.
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddSignIn(Configuration);
    services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme,
        options => {
            var redirectToIdpHandler = options.Events.OnRedirectToIdentityProvider;
            options.Events.OnRedirectToIdentityProvider = async context =>
            {
                // Call what Microsoft.Identity.Web is doing
                await redirectToIdpHandler(context);

                // Override the redirect URI to be what you want
                if(Configuration["AzureAd:WebAppURI"] != null)
                {
                    context.ProtocolMessage.RedirectUri = Configuration["AzureAd:WebAppURI"] + Configuration["AzureAd:CallbackPath"];
                }
            };

            var redirectToIdpForSignOutHandler = options.Events.OnRedirectToIdentityProviderForSignOut;
            options.Events.OnRedirectToIdentityProviderForSignOut = async context =>
            {
                // Call what Microsoft.Identity.Web is doing
                await redirectToIdpForSignOutHandler(context);

                // Override the redirect URI to be what you want
                if (Configuration["AzureAd:WebAppURI"] != null)
                {
                    context.ProtocolMessage.PostLogoutRedirectUri = Configuration["AzureAd:WebAppURI"] + Configuration["AzureAd:SignedOutCallbackPath"];
                }
            };
        });

    // More code here ...
}
```

**Comment by jmprieur** [comment]
Awesome @mochr for confirming.
cc: @jennyf19 @pmaytak

**Comment by BurritoSmith** [comment]
@jmprieur @jennyf19 I can confirm your suggested additions to the startup.cs file are also working in my above described environment.  I agree with @mochr that your suggested change is more ideal however so I will wait to wait to re-implement this for our .net core 2.2 to .net core 3.1 upgrade when you have things finalized.  Thanks so much for your work on this!

**Comment by mochr** [comment]
Thanks for the quick response, but I don't think this issue is fully fixed. When i run the 1-2-AnyOrg example, the `BuildConfidentialClientApplicationAsync` is not run at all. It is the `OpenIdConnectHandler` from `Microsoft.AspNetCore.Authentication.OpenIdConnect` that seems to handle the sign in and sign out actions. This use the `CallbackPath` and `SignedOutCallbackPath` from `OpenIdConnectOptions`, which does not allow absolute URIs.

**Comment by jmprieur** [comment]
@mochr : did you use your own version of Microsoft.Identity.Web (that you rebuilt yourself)?
we have not released Microsoft.Identity.Web-0.1.2-preview yet. 

Fixed mean in master
The issue will be closed when we have released - should be today

cc: @jennyf19

**Comment by mochr** [comment]
Yes, I have added the master branch as a dependency to the example project, and built from source.

**Comment by jmprieur** [comment]
Oh, I see, this does not work for the first leg of the Auth code flow handled by the Web app when the user signs-in.

**Comment by jmprieur** [comment]
@mochr : do you want to try again?
https://github.com/AzureAD/microsoft-identity-web/issues/115#issuecomment-618984571

**Comment by mochr** [comment]
I have tested it in Azure App Service for Linux containers, and now it works! Thanks again 👏

**Comment by jmprieur** [comment]
Thanks for confirming, @mochr 
Do you need us to release urgently?

**Comment by mochr** [comment]
No, there is no need to rush the next release for me. I guess the next release will be out soon anyway (within 2-3 weeks).

**Comment by krispenner** [comment]
For many people who only want to ensure https is used (instead of http) like myself as I'm running in a Docker container hosted in Azure App Service. I think a simpler option such as `ForceHttpsRedirectUris = true` in the configuration/options would be simpler. It would remove the need to specify the full absolute URI just to ensure https is used allowing the computed redirect URI to stay and just upgrade it to https. I'm concerned with managing the absolute URIs across configuration files and environments - relative paths as so much friendlier.

Here is what I've currently done which solved my issue of http being used when in a Docker container:
```
services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme,
    options => {
        var redirectToIdpHandler = options.Events.OnRedirectToIdentityProvider;
        options.Events.OnRedirectToIdentityProvider = async context =>
        {
            // Call what Microsoft.Identity.Web is doing
            await redirectToIdpHandler(context);

            // Override the redirect URI to be what you want
            if (context.ProtocolMessage?.RedirectUri?.StartsWith("http://") ?? false)
            {
                context.ProtocolMessage.RedirectUri = context.ProtocolMessage.RedirectUri.Replace("http://", "https://");
            }
        };

        var redirectToIdpForSignOutHandler = options.Events.OnRedirectToIdentityProviderForSignOut;
        options.Events.OnRedirectToIdentityProviderForSignOut = async context =>
        {
            // Call what Microsoft.Identity.Web is doing
            await redirectToIdpForSignOutHandler(context);

            // Override the redirect URI to be what you want
            if (context.ProtocolMessage?.PostLogoutRedirectUri?.StartsWith("http://") ?? false)
            {
                context.ProtocolMessage.PostLogoutRedirectUri = context.ProtocolMessage.PostLogoutRedirectUri.Replace("http://", "https://");
            }
        };
    });
```

**Comment by jennyf19** [comment]
@BurritoSmith @mochr Included in [0.1.3-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.3-preview)
@krispenner - so you know @jmprieur will be opening a new issue for the feature you asked for here.

**Comment by BurritoSmith** [comment]
@jennyf19 @jmprieur Thanks so much guys for your work on this.  I haven't been following this super closely since I've been pretty crazy busy with several projects but I'm curious if this release will work on the first leg of the authentication process.  @jmprieur mentioned above that a prior version would not and that's actually the only place I need it as I'm not using MSAL for my client-side stuff.

Thanks again for all your efforts!

**Comment by jmprieur** [comment]
Yes, @BurritoSmith it will work on the first leg of the authentication process.
Thanks for your feedback. We appreciate much!

**Comment by AAGhotkar** [comment]
> I have tested it in Azure App Service for Linux containers, and now it works! Thanks again 👏

@mochr Can you please share working code sample. I'm still getting same error. Updated all nuget packages but still problem persists.

When I run application locally then it works but problem comes only when I deploy to Azure App Service (Container-linux). 

@jmprieur  It should have worked seamlessly but facing issues. Not sure why its not called out specifically with given fix (code sample) in any of the forum.

**Comment by mochr** [comment]
@AAGhotkar Are you using version 0.1.3-preview of the Microsoft.Identity.Web and Microsoft.Identity.Web.UI packages?

Did you add the app settings for `RedirectUri` and `PostLogoutRedirectUri` in your configuration?
```
  {
    "name": "AzureAd__PostLogoutRedirectUri",
    "value": "https://<your app service name>.azurewebsites.net/signout-callback-oidc",
    "slotSetting": false
  },
  {
    "name": "AzureAd__RedirectUri",
    "value": "https://<your app service name>.azurewebsites.net/signin-oidc",
    "slotSetting": false
  },
```

And did you configure your app registration in Azure Ad with the redirect URI `https://<your app service name>.azurewebsites.net/signin-oidc`?

**Comment by jmprieur** [comment]
@AAGhotkar where would you suggest we add it? templates? wiki page? samples?

**Comment by BurritoSmith** [comment]
@jmprieur traditionally, detailed examples should go in the samples with a quick "how-to" on the home page of the repo.  If there are different multiple implementations, they should be well marked in the samples with each sample titled for the implementation.

**Comment by goshmiller** [comment]
@jmprieur I have read through this thread multiple times, and appreciate all of the suggestions.  I have not been able to find any way of getting this to work for a Server Side Razor application running in a container on Azure.  Is there a documentation example somewhere starting from scratch for a Blazor Server side App and deploying it to a container?

I, like the others can run from my local machine, but once deployed to Azure I get the following error:

> AADSTS50011: The repoly URL specified in the request does not match the reply URLs configured for the applicaiton. 

I [followed this pattern](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-app-configuration?tabs=aspnetcore) by starting with a blazor server side application in Visual Studio 2019, and changed out the v1 code for v2 code.  

The pattern there is different from the one above
i.e. 
`public class Startup
{
 ...
 // This method gets called by the runtime. Use this method to add services to the container.
 public void ConfigureServices(IServiceCollection services)
 {
  services.AddSignIn(Configuration, "AzureAd");

  services.AddRazorPages().AddMvcOptions(options =>
  {
   var policy = new AuthorizationPolicyBuilder()
                 .RequireAuthenticatedUser()
                 .Build();
   options.Filters.Add(new AuthorizeFilter(policy));
  }).AddMicrosoftIdentityUI();`

I have tried various ways to incorporate the suggestions above into this pattern, and not been able to get any to work.  (the closest that I have come is the application loops for a bit, then gets to a failure screen:
![image](https://user-images.githubusercontent.com/3017257/82935355-ecfb8100-9f5a-11ea-97a4-faf155acfce2.png)

Question to @mochr and @krispenner, what project type are you running this code in?  I like both of your suggestions. I just cant get either to work in my Blazor app.

**Comment by BurritoSmith** [comment]
@goshmiller when you see the reply url failure message, what is the reply url in your browser address bar?  That's the best way to troubleshoot any issues - make sure whatever that querystring variable is set to matches a valid reply url in your application in Azure.

**Comment by goshmiller** [comment]
@BurritoSmith Thanks for the suggestion.  I took a look, and in Chrome the redirect_uri parameter was exactly as it should be.

I then opened the application from Edge, and IE, and it worked there!  Now I need to dig into why Chrome won't work for authentication when the other browsers do.

To Re-create what I did, I start with Visual Studio 2019 starting a Blazor App, Server side, change Authentication to "Work or School Accounts", enable docker support.  

Then update the generated code from this:

```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => Configuration.Bind("AzureAd", options));

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });

            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddSingleton<WeatherForecastService>();
        }
```

With the code gleaned from above (and the other articles about migrating to v2)
To this:

```
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddSignIn(Configuration, "AzureAd");

            //https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-app-configuration?tabs=aspnetcore
            services.AddRazorPages().AddMvcOptions(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                              .RequireAuthenticatedUser()
                              .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();

            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme,
            options =>
            {
                var redirectToIdpHandler = options.Events.OnRedirectToIdentityProvider;
                options.Events.OnRedirectToIdentityProvider = async context =>
                {
                    // Call what Microsoft.Identity.Web is doing
                    await redirectToIdpHandler(context);

                    // Override the redirect URI to be what you want
                    if (context.ProtocolMessage?.RedirectUri?.StartsWith("http://") ?? false)
                    {
                        context.ProtocolMessage.RedirectUri = context.ProtocolMessage.RedirectUri.Replace("http://", "https://");
                    }
                };

                var redirectToIdpForSignOutHandler = options.Events.OnRedirectToIdentityProviderForSignOut;
                options.Events.OnRedirectToIdentityProviderForSignOut = async context =>
                {
                    // Call what Microsoft.Identity.Web is doing
                    await redirectToIdpForSignOutHandler(context);

                    // Override the redirect URI to be what you want
                    if (context.ProtocolMessage?.PostLogoutRedirectUri?.StartsWith("http://") ?? false)
                    {
                        context.ProtocolMessage.PostLogoutRedirectUri = context.ProtocolMessage.PostLogoutRedirectUri.Replace("http://", "https://");
                    }
                };
            });

            services.AddServerSideBlazor();
            services.AddSingleton<WeatherForecastService>();
        }
```

Then I deploy the container to the Azure Container Registry, with an App Service.  It now works for me in IE/Edge, but not Chrome.

**Comment by krispenner** [comment]
> so you know @jmprieur will be opening a new issue for the feature you asked for here.

Can you provide a link to the new issue so I can track it please?

FYI https://github.com/AzureAD/microsoft-identity-web/issues/115#issuecomment-627758989

**Comment by jmprieur** [comment]
My bad, @krispenner, I thought I had linked it. It's https://github.com/AzureAD/microsoft-identity-web/issues/175

It's assigned to @pmaytak

**Comment by graemeWT** [comment]
I have what appears to be this same issue when my web app is deployed on a HTTP server behind a HTTP reverse-proxy!
How do I discover when a fix is available?

**Comment by jmprieur** [comment]
We are in the process of releasing a new version at the moment, @graemeWT.
@pmaytak will tell you when this is done (should be today PST time)

Meanwhile, you can use the RedirectUri and PostLogoutRedirectUri properties of the appsettings.json.

**Comment by TimThaens** [comment]
Hi @jmprieur ,

I tried adding the RedirectUri and PostLogoutRedirectUri to the appsettings.json file, but AzureAD still gets the request with http://<myapp.mydomain.com>/signin-oidc.
I've tried using Microsoft.Identity.Web (and .UI) version 0.1.13-preview and 0.1.15-preview.

Just to be clear, where should we put this in the appsettings? as a new root child? Or as part of the "AzureAD" child?
 `
{
  "Logging": { ...},
  "AllowedHosts": "*",
  "AzureAd": { ... },
  "RedirectUri": 
   {
       "name": "AzureAd__RedirectUri",
       "value": "https://<myapp>.<mydomain>.com/signin-oidc",
       "slotSetting": false
   }  
}
`

or

`
{
  "Logging": { ...},
  "AllowedHosts": "*",
  "AzureAd": 
   {
       "Instance": "...",
       "Domain": "...",
       "TenantId": "...",
       "ClientId": "...",
       "CallbackPath": "/signin-oidc",
       "SignedOutCallbackPath": "/signout-callback-oidc",
       "ClientSecret": "...",
       "RedirectUri": 
       {
            "name": "AzureAd__RedirectUri",
            "value": "https://<myapp>.<mydomain>.com/signin-oidc",
            "slotSetting": false
       }  
   }
}
`
(The 2nd one seems to invalidate my Configuration)

**Comment by pmaytak** [comment]
Hi, @TimThaens. Please try the methods specified in article [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#forwarded-headers-middleware-order) to enable forwarded headers instead of using these redirect properties.

**Comment by jennyf19** [comment]
@BurritoSmith @goshmiller @graemeWT @TimThaens @krispenner 

We've been directed by the ASP .NET Core team to remove the MicrosoftIdentityOptions values of `RedirectUri`, `PostLogoutRedirectUri`, and `ForceHttpsRedirectUris` from the public API. These will be removed in the next release (0.2.0-preview). 

The AspNetCore guidance for working with proxies is [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1)

Address the issue centrally by using UseForwardedHeaders to fix up the request fields like scheme.

The container scenario should have been addressed by default in [.NET Core 3.0](https://devblogs.microsoft.com/aspnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/)

If there are issues with this for you, please contact the [ASP .NET Core team](https://github.com/dotnet/aspnetcore), as they will be the right team to assist with this. 

More [info](https://github.com/AzureAD/microsoft-identity-web/issues/223) here.

cc: @jmprieur @Tratcher

**Comment by graemeWT** [comment]
Hi,

Thanks for this email.
It is going to take me a while to work out what it means but I guess it is important.

Regards
Graeme

**Comment by TimThaens** [comment]
Many thanks, @jennyf19 
The AspNetCore guidance for working with proxies worked for me.

**Comment by jmprieur** [comment]
Thanks for confirming, @TimThaens 
and thanks for the heads-up @Tratcher

**Comment by jmprieur** [comment]
Updated the documentation [Deploying Web apps to App services as Linux containers](https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers)

**Comment by Maggy3** [comment]
Hi,

I have cretaed an ASP.Net Core 3.1 application with Azure AD authenticated. In my local I have not faced any issue because localhost is in exceptional list , when I hosted it on IIS on my dev server I am getting error like "The reply URL specified in the request does not match the reply URLs configured for the application: clientID". On Azure portal there is no option to register our URLs as 'http' but my dev server does not have SSL settings. How can we resolve this issue. Our web server is configured through load balancer. Can we do any settings in load balancer or from .net application. Could you please suggest me?

Thanks in Advance!!

Regards,
Maggy G

**Comment by jmprieur** [comment]
@Maggy3, did you see this section: https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers#issues-with-load-balancing-across-multiple-regions-using-front-door?

**Comment by djarvis** [comment]
I have gone through implementing the forwarded headers as described in https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers but I still get redirect_uri=http instead of https in my deployed linux container.  ASP.NET Core 3.1, Microsoft.Identity.Web 1.16.1, OpenIdConnect 3.1.19.

Is there anything else I missed besides:

`
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders =
                    Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedFor | Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto;
            });
`

and:

`
app.UseForwardedHeaders();
`

For now I'm going to implement the forcing of https through the redirect callback handler thing as described above since I need to move forward (no pun intended!) with this...

**Comment by jmprieur** [comment]
@tratcher, can you please help?

**Comment by djarvis** [comment]
I implemented the OnRedirectToIdentityProvider additions to one project that uses:

`services.AddAuthentication().AddOpenIdConnect()`

and it works fine, it redirects back to the modified https page and everything is handled well.

I have a second project that uses:

`services.AddAuthentication().AddMicrosoftIdentityWebApp()`

and it does redirect back to the modified https page but something in that signin-oidc code is erroring out, still saying that the reply URL (http) doesn't match the one in the app registration (https).  I cannot readily find the controller code that handles this callback to debug further.

And the forwarded headers doesn't work at all and I have no clue how to debug that further.

**Comment by Tratcher** [comment]
The scheme has to be changed in too many places for the OnRedirectToIdentityProvider approach to work reliably. Let's get the forwarders working instead.

Start with the troubleshooting steps at
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#troubleshoot

**Comment by djarvis** [comment]
@Tratcher This is a project that is built into a Linux container and then published to an Azure Web App.  Does there need to be something special done to the Azure load balancer or something?  What would I put into the KnownProxies?

**Comment by Tratcher** [comment]
Oh, there's a similar scenario here: https://github.com/dotnet/aspnetcore/issues/24151

If you're creating your own dockerfile then add the following:
https://github.com/Azure-App-Service/ImageBuilder/blob/0901682fa83f20ecd1ccab6612e8d357dcd15150/GenerateDockerFiles/dotnetcore/debian-9/Dockerfile#L56

**Comment by djarvis** [comment]
Ah yes.  Got it!

I'm wondering how I could have stumbled upon that any sooner.

After inserting that environment variable everything works.  I can now remove the past two day's worth of messy trial-and-error code I had going on to try to make this all happen.

Thanks!

**Comment by mekk1t** [comment]
I encountered the same situation using `OpenIdConnect` though.
This suggestion:
```cs
options.Events.OnRedirectToIdentityProvider = async context =>
     {
      // Call what Microsoft.Identity.Web is doing
      await redirectToIdpHandler(context);

     // Override the redirect URI to be what you want
     context.ProtocolMessage.RedirectUri = "your redirect URI";
     context.ProtocolMessage.PostLogoutRedirectUri = "your post logout URI";
```
worked for me. Confirmed.

**Comment by schivei** [comment]
Hi, I've been tried all suggestions here, but no one have solved my problem.

My configurations:

Program.cs
```csharp
...
services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
});
...
// first use
app.UseForwardedHeaders();
...
```

nginx.conf
```nginx
server {
        listen      80;
        listen      [::]:80;
        server_name sts.des.mycompany.com;
        access_log  off;
        error_log   off;
        return      301                     https://$server_name$request_uri;
}

server {
        listen              443       ssl;
        listen              [::]:443  ssl;
        server_name         sts.des.mycompany.com;
        ssl_certificate     /etc/nginx/ssl/bundle-sts.crt;
        ssl_certificate_key /etc/nginx/ssl/private-sts.key;
        ssl_protocols       SSLv3 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_session_timeout 1d;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_tickets off;
        ssl_stapling        off;

        add_header          X-Frame-Options         DENY;
        add_header          X-Content-Type-Options  nosniff;

        location /diag {
            alias         /usr/share/nginx/html/diag.txt;
            default_type  text/plain;
        }

        location / {
            proxy_pass                  https://sts-service:8443;
            proxy_ssl_server_name       on;
            proxy_ssl_name              $server_name;
            proxy_set_header            Host                  $host;
            proxy_set_header            Referer               $http_referer;
            proxy_set_header            X-Real-IP             $remote_addr;
            proxy_set_header            X-Forwarded-For       $proxy_add_x_forwarded_for;
            proxy_set_header            X-Forwarded-Proto     HTTPS;
            proxy_http_version          1.1;
            proxy_buffering             on;
            proxy_buffer_size           256k;
            proxy_buffers               4                     256k;
            proxy_set_header            Upgrade               $http_upgrade;
            proxy_set_header            Connection            $http_connection;
            proxy_cache_bypass                                $http_upgrade;
            proxy_redirect              off;
            port_in_redirect            off;

            limit_req                   zone=one burst=10 nodelay;
        }
}
```

Dockerfile
```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:$VERSION AS base
ENV DOTNET_RUNNING_IN_CONTAINER=true
ENV ASPNETCORE_URLS="http://+:8080;https://+:8443"
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV http_proxy="http://10.1.X.X:80"
ENV https_proxy="http://10.1.X.X:80"
ENV no_proxy="localhost"
RUN apk add --no-cache icu-libs
RUN apk add --no-cache icu-data-full
WORKDIR /app
EXPOSE 8080
EXPOSE 8443
RUN adduser \
  --disabled-password \
  --home /app \
  --gecos '' app \
  && chown -R app /app
USER app
```

Note: both http and https proxy need to point to http:// scheme, this is the way it is implemented on my company and I can't change it.

Any suggestion?

Regards.

**Comment by schivei** [comment]
@Tratcher, I do not have access to logs, some internal policies is required to take it.

But a I’ve been solved the problem, removing the first nginx block (:80 to :443 redirect) and leaving the application do the https redirection, no code changed.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-identity-web/issues/115

**Comment by RobK410** [comment]
This is still an issue in 2025, .NET 8.0. Microsoft.Identity.Web (3.8.4)

Why not simply always prefix "https" since you cannot configure an http redirect_uri in Azure ID? There's appears to be no clear definitive fix here on this issue chain.

My Scenario:

Runs fine locally, outside a Linux container
Production build to Linux container, into Azure App Service. Fails, as redirect is always "http" prefix.

I've implemented the header forwarding hack and still get the error. What was the Microsoft team code fix that closed this issue?
