### ISSUE TITLE
[Bug] RoleClaimType is not added to ClaimsIdentity

### ISSUE THREAD

**Issue by HWouters** [AzureAD/microsoft-identity-web#1218]
**Which version of Microsoft Identity Web are you using?**
This issue is only present in the latest version 1.11

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
b. The app is in production and I haven't upgraded Microsoft Identity Web, but started seeing this issue.

**Repro**

```csharp
 services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    Configuration.Bind("AzureAdB2C", options);
                    options.TokenValidationParameters.NameClaimType = "email";
                    options.TokenValidationParameters.RoleClaimType = "roles";
                    options.Events ??= new OpenIdConnectEvents();
                    options.Events.OnRedirectToIdentityProvider = OnRedirectToIdentityProvider;
                })
                .EnableTokenAcquisitionToCallDownstreamApi(scopes)
                .AddDistributedTokenCaches();
```

**Expected behavior**
"roles" is set as the RoleClaimType in the ClaimsIdentity (was working in v1.10)

**Actual behavior**
No matter what you configure in the TokenValidationParameters, the RoleClaimType is always: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

**Comment by jennyf19** [comment]
thanks @HWouters this will go in the 1.12 release, scheduled for mid-late next week (week of June 1)

**Comment by jmprieur** [comment]
@HWouters this is fixed in 1.12.0 which released today

**Comment by y2kbugger** [comment]
@jennyf19 I think I still get this on current (and 1.10.0 1.11.0, 1.12.0) my setup might be different or I might be misunderstanding what these settings do.

I can say that the following settings have no effect on what comes out the the `AuthenticationStateProvider` (`Microsoft.AspNetCore.Components.Server.ServerAuthenticationStateProvider`)

```
            services
                .AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(
                    options =>
                    {
                        Configuration.Bind("AzureAd", options);
                        options.TokenValidationParameters.NameClaimType = "email";
                        options.TokenValidationParameters.RoleClaimType = "roles";
                    });
```

**Comment by mcmorry** [comment]
I'm experiencing the exact same issue. I'm using 1.23.0 in .NET 6. 
Do you have any examples I can use to compare with my code?
