### ISSUE TITLE
[Bug] ValidIssuers is not applied

### ISSUE THREAD

**Issue by jc4gh** [AzureAD/microsoft-identity-web#1360]
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.15.1

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [x] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**
Get a token from Tenant1 and call API.

```csharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApi(this.Configuration.GetSection("AzureAd"), subscribeToJwtBearerMiddlewareDiagnosticsEvents: true);

services.Configure(JwtBearerDefaults.AuthenticationScheme, (JwtBearerOptions options) =>
{
    var existingOnTokenValidatedHandler = options.Events.OnTokenValidated;
    options.Events.OnTokenValidated = async context =>
    {
        await existingOnTokenValidatedHandler(context);

        // Your code to add extra configuration that will be executed after the current event implementation.
        options.TokenValidationParameters.ValidIssuers = new[] { "https://sts.windows.net/[Tenant2 GUID]/" };
        options.TokenValidationParameters.ValidAudiences = new[] { "[audience]" };
    };
});
```

**Expected behavior**
The request gets 401.

**Actual behavior**
"Successfully validated the token." and passes validation.

**Additional context / logs / screenshots**
Above code is from https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration#customizing-token-validation.

**Comment by jennyf19** [comment]
@jc-msft try moving the condition for validating the token to before it's validated. that should resolve the issue. 

```csharp
services.Configure(JwtBearerDefaults.AuthenticationScheme, (JwtBearerOptions options) =>
{
     // Your code to add extra configuration that will be executed after the current event implementation.
     options.TokenValidationParameters.ValidIssuers = new[] { "https://sts.windows.net/[Tenant2 GUID]/" };
     options.TokenValidationParameters.ValidAudiences = new[] { "[audience]" };
     
     var existingOnTokenValidatedHandler = options.Events.OnTokenValidated;

     options.Events.OnTokenValidated = async context =>
     {
          await existingOnTokenValidatedHandler(context);
     };
});
```

**Comment by jennyf19** [comment]
i believe this is resolved. closing, but feel free to reopen

**Comment by jc-msft** [comment]
It still doesn't seem to validate.
Token:
![image](https://user-images.githubusercontent.com/82118227/128776192-95f79b9d-6e04-4049-a897-e29e3a7a8f06.png)

Code:
![image](https://user-images.githubusercontent.com/82118227/128776699-712d3034-fad0-4645-9570-c9902a455f82.png)

![image](https://user-images.githubusercontent.com/82118227/128776816-be892b79-6cc0-4085-a8d3-3dbb454e7836.png)

**Comment by jc-msft** [comment]
@jennyf19 I can't seem to reo-pen.

**Comment by thecodetinker** [comment]
I was very glad to stumble across this issue, because I've been trying for hours to understand why my code has stopped working after migrating to `Microsoft.Identity.Web`! Can you please recommend a workaround until this is fixed (hopefully soon - seems like a pretty major security hole)? Something like the following maybe?

``` csharp
services
        .AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
        .AddMicrosoftIdentityWebApp(options =>
        {
          options.Events = new OpenIdConnectEvents
          {
            OnTokenValidated = async context =>
            {
              await existingOnTokenValidatedHandler(context);

              if (validIssuers.Length > 0 && !validIssuers.Any(iss => iss == context.SecurityToken.Issuer))
              {
                context.HandleResponse();
                context.Response.Redirect($"{baseUrl}/Account/AccessDenied");
              }
            }
          };
        });
`

**Comment by jmprieur** [comment]
@jpda @thecodetinker 
I investigated, and it turns out that ASP.NET Core always adds an issuer to the TokenValidationParameters.Issuers. The Issuer which is fetched from the OpenIdConnectConfiguration (From the `issuer` property of the `https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration` metadata document)

Then the other ValidIssuers are appended to this one.

This is happening here:

https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L101

In order to avoid this behavior, I recommend that you also override the [`IssuerValidator`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.issuervalidator?view=azure-dotnet) delegate to match the issuer with only your valid issuers.

I'm going to start a conversation with the ASP.NET Core team to understand if there is a better option.
cc: @tratcher

**Comment by thecodetinker** [comment]
Hi again and thanks for the update. I'm a bit unsure about overriding the `IssuerValidator` delegate - from what I can see the default does a lot of checking that would need replicating. Did you have any luck with the ASP.NET Core team, or the possible solutions proposed by @jpda ?

**Comment by jmprieur** [comment]
@tratcher do we want to do something about the fact that ASP.NET Core systematically adds the ClientId as a valid issuer?
(note that this would be a breaking change)
