### ISSUE TITLE
NullReferenceException is thrown when using DefaultTokenAcquisitionHost and trying to acquire a token

### ISSUE THREAD

**Issue by MZOLN** [AzureAD/microsoft-identity-web#2394]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.13.3

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

NRE thrown in the pasted stack.
The issue is that the defaultokenacquisitionhost returns a null redirecturi but msal assumes that it`s not null

### Reproduction steps

Create console app
Call downstream api

### Error message

System.NullReferenceException

  HResult=0x80004003

  Message=Object reference not set to an instance of an object.

  Source=Microsoft.Identity.Web.TokenAcquisition

  StackTrace:

   at Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal() in /_/src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs:line 452

   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions) in /_/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs:line 580

   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions) in /_/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs:line 566

   at Microsoft.Identity.Web.TokenAcquisition.<GetAuthenticationResultForUserAsync>d__14.MoveNext() in /_/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs:line 235

 

  This exception was originally thrown at this call stack:

    Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal() in MergedOptions.cs

    Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(Microsoft.Identity.Web.MergedOptions) in TokenAcquisition.cs

    Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(Microsoft.Identity.Web.MergedOptions) in TokenAcquisition.cs

    Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(System.Collections.Generic.IEnumerable<string>, string, string, string, System.Security.Claims.ClaimsPrincipal, Microsoft.Identity.Web.TokenAcquisitionOptions) in TokenAcquisition.cs

### Relevant code snippets

```csharp
Run ConsoleApp2 on MISE repo
```

### Regression

Id Web 2.13.3

### Expected behavior

Token is acquired.

**Comment by jennyf19** [comment]
@MZOLN Do you have everything in the appsettings.json? Is the authority, instance, etc... all present?

**Comment by MZOLN** [comment]
Those are the settings:
        "me": {
            "BaseUrl": "https://graph.microsoft.com/v1.0",
            "RelativePath": "/me",
            "Scopes": [ "user.read" ],
            "AcquireTokenOptions": {
                "AuthenticationOptionsName": "S2SAuthentication"
            }
            
            Is anything missing?

**Comment by Jan1503** [comment]
I encounter the same issue with 2.13.3.
It's working in 2.13.2.
Haven't found the time to further debug it, just switched back to 2.13.2.

Short Stack Trace:
`System.NullReferenceException:
   at Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal (Microsoft.Identity.Web.TokenAcquisition, Version=2.13.3.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae)
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication (Microsoft.Identity.Web.TokenAcquisition, Version=2.13.3.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication (Microsoft.Identity.Web.TokenAcquisition, Version=2.13.3.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync (Microsoft.Identity.Web.TokenAcquisition, Version=2.13.3.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae)
   at Microsoft.Identity.Web.TokenAcquisition+<GetAccessTokenForAppAsync>d__17.MoveNext (Microsoft.Identity.Web.TokenAcquisition, Version=2.13.3.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)`

**Comment by jmprieur** [comment]
@Jan1503 : Marcin's error was with is code (he forgot to configure the MicrosoftIdentityApplicationOptions)
how did you configure your application

**Comment by Jan1503** [comment]
@jmprieur : Here's my auth-config:

```cs
public static IServiceCollection AddDefaultAuthentication(this IServiceCollection services,
        IConfigurationSection azureAdConfigurationSection)
    {
        ArgumentNullException.ThrowIfNull(azureAdConfigurationSection);
        
        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApi(jwt =>
            {
                IdentityModelEventSource.ShowPII = true;
                var opt = new MicrosoftIdentityOptions();
                azureAdConfigurationSection.Bind(opt);

                jwt.Authority = $"https://sts.windows.net/{opt.TenantId}/v2.0";
                jwt.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = $"https://sts.windows.net/{opt.TenantId}",
                    ValidAudiences = new List<string>
                    {
                        opt.ClientId!,
                        $"api://{opt.ClientId}"
                    }
                };
                jwt.Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = ctx => Task.CompletedTask
                };
            }, azureAdConfigurationSection.Bind)

            .EnableTokenAcquisitionToCallDownstreamApi(options => { })
            .AddInMemoryTokenCaches();

        return services;
    }
```

**Comment by jmprieur** [comment]
@Jan1503 this should be fixed in 2.15.0 that is going to release tomorrow

**Comment by slabarque** [comment]
Still not fixed apparently. I'm having this issue with the daemon_console sample from https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/1-Call-MSGraph

I was following this Quickstart guide:
https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-console-app-netcore-acquire-token
