### ISSUE TITLE
Clear user token from cache and acquire token from AAD in on-behalf-of flow

### ISSUE THREAD

**Issue by snehanagendra** [AzureAD/microsoft-identity-web#532]
**Is your feature request related to a problem? Please describe.**
We are using MSAL and Microsoft.Identity.Web library for on-behalf-of token acquisition. We have token caching enabled via the Identity.Web library and we are looking for a way to clear the user token cache and acquire a token from AAD in certain flows.

**Describe the solution you'd like**
We would like to be able to invoke an API, say, on the ITokenAcquisition that would clear the token cache for the current user, and obtain a new token from AAD

**Describe alternatives you've considered**

**Additional context**

**Comment by jmprieur** [comment]
@jennyf19, @pmaytak, @henrik-me: we could expose an optional delegate (here and in downstreamApi options) to provide more options:
- @snehanagendra : would a `forceRefresh` boolean work for your scenario? 
- another ask is to expose `extraQueryParameters`. See https://github.com/AzureAD/microsoft-identity-web/issues/561

**Comment by 3GDXC** [comment]
@jmprieur what is the defaults for caching; is the duration of the token cache based on the token expiry? its not clear what the default behavior of the token cache is? and this would IMHO lead to confusions I feel the token caching needs some work/explanations and considerations around when/what/if hooks are needed and/or the ability to remove/flush/clear tokens added to the cache based on datetime or age is required.

**Comment by snehanagendra** [comment]
@jmprieur Yes, a forceRefresh flag would work

**Comment by jmprieur** [comment]
Addressed in https://github.com/AzureAD/microsoft-identity-web/pull/596/files

**Comment by jmprieur** [comment]
@snehanagendra, the fix is available in Microsoft.Identity.Web 1.0.0
there is a new class named `TokenAcquisitionOptions` which has a `ForceRefresh` boolean property. Here is how to use it:
https://github.com/AzureAD/microsoft-identity-web/wiki/customization#customizations-to-acquire-tokens.

Proposing to close this issue. Feel free to reopen if that does not work for you.

**Comment by scastria** [comment]
I have set the ForceRefresh to true and yet when I acuire a token, I still see ForceRefresh: False printed out in the log and I don't get a new token.  It is the same one as last time.

**Comment by MarcosMusa** [comment]
I have the below configuration but Force Refresh still doesn't work, the token it´s the same one as last time.

`public async Task<AuthenticationResult> GetAccessTokenAsync()
=> await _tokenAcquisition.GetAuthenticationResultForUserAsync(scopes: new string[] { "https://exemple/.default" }
                    , tokenAcquisitionOptions: new TokenAcquisitionOptions() { ForceRefresh = true });`
